import { ArrowRight, CheckCircle2, FileText, LoaderCircle, RotateCcw, ScanLine } from 'lucide-react';
import type { ExtractionResult, PreparedResume } from './types';

interface Props {
  extraction: ExtractionResult; text: string; reviewed: boolean; prepared: PreparedResume | null;
  busy: boolean; preparing: boolean; jobValid: boolean; error: string;
  onTextChange: (text: string) => void; onReviewedChange: (reviewed: boolean) => void;
  onRestore: () => void; onPrepare: () => void;
}

export function ExtractionPreview({ extraction, text, reviewed, prepared, busy, preparing, jobValid, error, onTextChange, onReviewedChange, onRestore, onPrepare }: Props) {
  const sections = prepared?.resume_sections ?? extraction.sections;
  const edited = text !== extraction.text;
  return <section className="results preview" aria-labelledby="preview-title">
    <div className="section-heading"><div><span className="eyebrow">02 / 03 Â· CHECK THE DETAILS</span><h2 id="preview-title">Review your extracted resume</h2></div><span className="pill"><FileText size={14} />{extraction.file_type.toUpperCase()}{extraction.page_count !== null ? ` Â· ${extraction.page_count} page${extraction.page_count === 1 ? '' : 's'}` : ''}{extraction.ocr_used ? ' Â· OCR used' : ''}</span></div>
    <div className="preview-grid"><div className="card"><div className="card-title"><FileText size={19} /><h3>Your resume text</h3><button className="text-button restore-button" disabled={busy || !edited} onClick={onRestore} type="button"><RotateCcw size={13} />Restore original</button></div><label className="preview-label" htmlFor="resume-text">Check that your skills, projects, experience, and education are complete. Correct missing text or reading order below.</label><textarea id="resume-text" className="resume-editor" value={text} maxLength={50000} disabled={busy} onChange={event => onTextChange(event.target.value)} aria-describedby="resume-text-help" /><div className="textarea-help" id="resume-text-help"><span>{edited ? 'Edited text Â· confirm your review again' : 'Extracted from your uploaded document'}</span><span>{text.length.toLocaleString()} / 50,000</span></div><label className="review-checkbox"><input type="checkbox" checked={reviewed} disabled={busy} onChange={event => onReviewedChange(event.target.checked)} /><span>Iâ€™ve checked the text for completeness and reading order.</span></label>{!jobValid ? <p className="preview-hint">Add a job description of at least 100 characters above to continue.</p> : null}{text.trim().length < 40 ? <p className="preview-hint">At least 40 characters of readable resume text are required.</p> : null}{error ? <div className="error" role="alert">{error}</div> : null}<button className="analyze-button prepare-button" type="button" disabled={busy || !reviewed || !jobValid || text.trim().length < 40} onClick={onPrepare}>{preparing ? <><LoaderCircle className="spin" size={18} />Extracting skillsâ€¦</> : <>Extract skills & requirements<ArrowRight size={18} /></>}</button></div>
      <aside className="card"><div className="card-title"><ScanLine size={19} /><h3>Extraction checks</h3></div><span className={`readability-badge ${extraction.readability.status}`}>{extraction.readability.status === 'readable' ? 'Text extracted successfully' : 'Review recommended'}</span><ul className="extraction-issues">{extraction.readability.issues.length > 0 ? extraction.readability.issues.map((issue, index) => <li key={index}>{issue}</li>) : <li>No extraction issues detected. Still check that all important content is present.</li>}</ul><div className="section-list"><h4>{prepared ? 'Sections from your reviewed text' : edited ? 'Original sections Â· update by preparing text' : 'Detected sections'}</h4>{sections.map((section, index) => <details key={`${section.name}-${index}`}><summary>{section.name}<span>{section.text.length} characters</span></summary><p>{section.text}</p></details>)}</div>{extraction.pages.length > 1 ? <details className="page-details"><summary>Text by PDF page</summary>{extraction.pages.map(page => <div key={page.number}><h4>Page {page.number} Â· {page.method}</h4><p>{page.text || 'No text found.'}</p></div>)}</details> : null}<p className="result-footnote">{extraction.warnings.join(' ')}</p></aside></div>
    {prepared ? <div className="prepared-panel" role="status"><CheckCircle2 size={24} /><div><h3>Skills and requirements extracted</h3><p>Found {prepared.resume_skills.length} canonical resume skills and {prepared.job_requirements.length} job requirements.</p><p className="prepared-next">Review the evidence and requirement categories below. Confirm the categories below before comparing.</p></div></div> : null}
  </section>;
}
